# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Linux
#  timeoutInMinutes: 0
  pool:
    vmImage: 'ubuntu-latest'
  steps:
      - script: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH
      - script: |
            echo hello from Linux
            
            echo installation conda-forge
            conda install conda-forge
            
            echo installation anaconda
            conda install anaconda
            
            echo installation bioconda
            conda install bioconda
            
            echo installation pandas
            conda install pandas
            
            echo installation entrez-direct
            conda install entrez-direct
            
            echo installation primer3-py
            conda install primer3-py
            
            echo installation bedtools
            conda install bedtools
            
            echo installation mmseqs2
            conda install mmseqs2
            
            echo installation seqkit
            conda install seqkit
            
            echo installation genmap
            conda install genmap
            
            echo installation primer3
            conda install primer3
            
            echo installation biopython
            conda install biopython
            
            echo installation finished
            python probeit.py --help
            python probeit.py posnegset --help
            python probeit.py snp --help
- job: macOS
#  timeoutInMinutes: 0
  pool:
    vmImage: 'macOS-latest'
  steps:
      - script: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH

        # On Hosted macOS, the agent user doesn't have ownership of Miniconda's installation directory/
        # We need to take ownership if we want to update conda or install packages globally
      - script: sudo chown -R $USER $CONDA
        displayName: Take ownership of conda installation
      - script: |
            echo hello from macOS
            
            echo installation conda-forge
            conda install conda-forge
            
            echo installation anaconda
            conda install anaconda
            
            echo installation bioconda
            conda install bioconda
            
            echo installation pandas
            conda install pandas
            
            echo installation entrez-direct
            conda install entrez-direct
            
            echo installation primer3-py
            conda install primer3-py
            
            echo installation bedtools
            conda install bedtools
            
            echo installation mmseqs2
            conda install mmseqs2
            
            echo installation seqkit
            conda install seqkit
            
            echo installation genmap
            conda install genmap
            
            echo installation primer3
            conda install primer3
            
            echo installation biopython
            conda install biopython
            
            echo installation finished
            python probeit.py --help
            python probeit.py posnegset --help
            python probeit.py snp --help

