# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Linux
  timeoutInMinutes: 120
  pool:
    vmImage: 'ubuntu-latest'
  steps:
      - script: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH
      - script: |
            echo hello from Linux
            conda install pandas -y
            conda install entrez-direct -y
            conda install primer3-py -y
            conda install bedtools -y
            conda install mmseqs2 -y
            conda install seqkit -y
            conda install genmap -y
            conda install primer3 -y
            conda install biopython -y
            echo <run probeit>
            python probeit.py --help
            python probeit.py posnegset --help
            python probeit.py snp --help
            pwd
            ls
- job: macOS
  timeoutInMinutes: 120
  pool:
    vmImage: 'macOS-latest'
  steps:
      - script: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH

        # On Hosted macOS, the agent user doesn't have ownership of Miniconda's installation directory/
        # We need to take ownership if we want to update conda or install packages globally
      - script: sudo chown -R $USER $CONDA
        displayName: Take ownership of conda installation
      - script: |
            echo hello from macOS
            conda install pandas -y
            conda install entrez-direct -y
            conda install primer3-py -y
            conda install bedtools -y
            conda install mmseqs2 -y
            conda install seqkit -y
            conda install genmap -y
            conda install primer3 -y
            conda install biopython -y
            echo <run probeit>
            python probeit.py --help
            python probeit.py posnegset --help
            python probeit.py snp --help
            pwd
            ls

