# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Linux
  timeoutInMinutes: 120
  pool:
    vmImage: 'ubuntu-latest'
  steps:
      - script: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH
      - script: |
            echo  hello from Linux
            echo  create env
            conda create -n probeit -c conda-forge -c anaconda -c bioconda pandas entrez-direct fire primer3-py bedtools  mmseqs2 seqkit genmap primer3 biopython -y -v
            echo  activate env
            source activate probeit
            conda info —envs
            mmseqs -h
            echo  run probeit help
            python probeit.py --help
            python probeit.py posnegset --help
            python probeit.py snp --help
            echo  run probeit posnegset
            python probeit.py posnegset -p sample/positive.fasta -n sample/negative.fasta -o posnegset1
            head posnegset1/cluster/genomes.clu_rep_seq.fasta
            echo  run probeit snp
            python probeit.py snp -r sample/ref.fasta -a sample/ref.gff -s sample/str.fasta  -p "10,11,19,20,21,22" -m "nt:A21716G,nt:G23011A,nt:G23592C,nt:T24223C,nt:C26304T,nt:T26766C,nt:A21716G" -o snp1
            pwd
            ls
- job: macOS
  timeoutInMinutes: 120
  pool:
    vmImage: 'macOS-latest'
  steps:
      - script: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH

        # On Hosted macOS, the agent user doesn't have ownership of Miniconda's installation directory/
        # We need to take ownership if we want to update conda or install packages globally
      - script: sudo chown -R $USER $CONDA
        displayName: Take ownership of conda installation
      - script: |
            echo  hello from macOS
            echo  create env
            conda create -n probeit -c conda-forge -c anaconda -c bioconda pandas entrez-direct fire primer3-py bedtools  mmseqs2 seqkit genmap primer3 biopython -y -v
            echo  activate env
            source activate probeit
            conda info —envs
            mmseqs -h
            echo  run probeit help
            python probeit.py --help
            python probeit.py posnegset --help
            python probeit.py snp --help
            echo  run probeit posnegset
            python probeit.py posnegset -p sample/positive.fasta -n sample/negative.fasta -o posnegset2
            head posnegset2/cluster/genomes.clu_rep_seq.fasta
            echo  run probeit snp
            python probeit.py snp -r sample/ref.fasta -a sample/ref.gff -s sample/str.fasta  -p "10,11,19,20,21,22" -m "nt:A21716G,nt:G23011A,nt:G23592C,nt:T24223C,nt:C26304T,nt:T26766C,nt:A21716G" -o snp2
            pwd
            ls

