# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
      - script: |
            echo hello from Linux
            conda create -n probeit -c conda-forge -c anaconda -c bioconda pandas entrez-direct fire primer3-py bedtools  mmseqs2 seqkit genmap primer3 biopython
            conda activate probeit
            python probeit.py --help
            python probeit.py posnegset --help
            python probeit.py snp --help
- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
      - script: |
            echo hello from macOS
            conda create -n probeit -c conda-forge -c anaconda -c bioconda pandas entrez-direct fire primer3-py bedtools  mmseqs2 seqkit genmap primer3 biopython
            conda activate probeit
            python probeit.py --help
            python probeit.py posnegset --help
            python probeit.py snp --help
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
      - script: |
            echo hello from Windows
            conda create -n probeit -c conda-forge -c anaconda -c bioconda pandas entrez-direct fire primer3-py bedtools  mmseqs2 seqkit genmap primer3 biopython
            conda activate probeit
            python probeit.py --help
            python probeit.py posnegset --help
            python probeit.py snp --help
