# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Linux
  timeoutInMinutes: 120
  pool:
    vmImage: 'ubuntu-latest'
  steps:
      - script: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH
      - script: |
            echo HELLO FROM Linux
            echo [process] create env
            conda create -n probeit -c conda-forge -c anaconda -c bioconda pandas entrez-direct primer3-py bedtools  mmseqs2 seqkit genmap primer3 biopython -y -v
            echo [process] activate env
            source activate probeit
            conda info —envs
            
            echo [process] make setcover
            cd setcover
            make
            echo ====== makefile ======
            head -30 Makefile
            echo ====== makefile ======
            cd ..
            
            echo [process] run probeit posnegset
            python probeit.py posnegset -p sample/positive.fasta -n sample/negative.fasta -o posnegset1
            echo [process] run probeit snp
            python probeit.py snp -r sample/ref.fasta -a sample/ref.gff -s sample/str.fasta  -p "10,11,19,20,21,22" -m "aa:orf1ab:L4715F,aa:S:Q52R,aa:S:E484K,aa:S:Q677H,aa:S:F888L,aa:E:L21F,aa:M:I82T" -o snp1
            
            echo [process] compare outputs
            echo posnegset 1
            diff posnegset1/sorted1.fa sample/posnegset_1.fa
            echo posnegset 2
            diff posnegset1/sorted2.fa sample/posnegset_2.fa
            echo snp aa 1
            diff snp1/sorted1.fa sample/snp_aa_1.fa
            echo snp aa 2
            diff snp1/sorted2.fa sample/snp_aa_2.fa
- job: macOS
  timeoutInMinutes: 120
  pool:
    vmImage: 'macOS-latest'
  steps:
      - script: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH

      - script: sudo chown -R $USER $CONDA
        displayName: Take ownership of conda installation
      - script: |
 
            echo HELLO FROM MacOS
            echo [process] create env
            conda create -n probeit -c conda-forge -c anaconda -c bioconda pandas entrez-direct primer3-py bedtools  mmseqs2 seqkit genmap primer3 biopython -y -v
            echo [process] activate env
            source activate probeit
            conda info —envs
            
            echo [process] make setcover
            cd setcover
            make
            echo ====== makefile ======
            head -30 Makefile
            echo ====== makefile ======
            cd ..
            
            echo [process] run probeit posnegset
            python probeit.py posnegset -p sample/positive.fasta -n sample/negative.fasta -o posnegset2
            echo [process] run probeit snp
            python probeit.py snp -r sample/ref.fasta -a sample/ref.gff -s sample/str.fasta  -p "10,11,19,20,21,22" -m "nt:A21716G,nt:G23011A,nt:G23592C,nt:T24223C,nt:C26304T,nt:T26766C,nt:A21716G" -o snp2
            
            echo [process] compare outputs
            echo posneget 1
            diff posnegset2/sorted1.fa sample/posnegset_1.fa
            echo posnegset 2
            diff posnegset2/sorted2.fa sample/posnegset_2.fa
            echo snp nt 1
            diff snp2/sorted1.fa sample/snp_nt_1.fa
            echosnp nt 2
            diff snp2/sorted2.fa sample/snp_nt_2.fa


